# Generated by Django 2.1.4 on 2019-10-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinelabApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(default='', max_length=100)),
                ('seq', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('solution_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='', max_length=20)),
                ('judges', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=20)),
                ('business_type', models.CharField(default='', max_length=20)),
                ('industry_type', models.CharField(default='', max_length=20)),
                ('total_score', models.IntegerField(default=0)),
            ],
        ),
    ]
