# Generated by Django 2.1.4 on 2019-10-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinelabApp', '0002_detailscore_scoretable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailscore',
            name='solution_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='OnlinelabApp.ScoreTable'),
        ),
    ]
