# Generated by Django 2.1.4 on 2019-10-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinelabApp', '0004_auto_20191010_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoretable',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
